/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.francodavyd.vista;

import com.sun.source.tree.BreakTree;
import java.awt.Color;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;

/**
 *
 * @author Ema
 */
public class CalcularEntreFechas extends javax.swing.JPanel {

    /**
     * Creates new form CalcularEntreFechas
     */
    public CalcularEntreFechas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFecha1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFecha2 = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMostrar = new javax.swing.JTextArea();
        btnActual = new javax.swing.JButton();
        txtHora1 = new javax.swing.JTextField();
        txtHora2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(613, 290));

        jLabel1.setText("Ingresa la primer fecha: (dd/MM/yyyy)");

        jLabel2.setText("Ingresa la segunda fecha: (dd/MM/yyyy)");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        txtMostrar.setEditable(false);
        txtMostrar.setBackground(new java.awt.Color(255, 255, 255));
        txtMostrar.setColumns(20);
        txtMostrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMostrar.setRows(5);
        txtMostrar.setAutoscrolls(false);
        txtMostrar.setBorder(null);
        jScrollPane1.setViewportView(txtMostrar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnActual.setText("Fecha y hora actual");
        btnActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualActionPerformed(evt);
            }
        });

        jLabel3.setText("Hora: (Ej: 00:00, Opcional)");

        jLabel4.setText("Hora: (Ej: 00:00, Opcional)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnCalcular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFecha1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFecha2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtHora2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnActual))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(txtHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHora2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActual))
                .addGap(26, 26, 26)
                .addComponent(btnCalcular)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        String fecha1 = txtFecha1.getText();
        String fecha2 = txtFecha2.getText();
        String fecha1sub = fecha1.substring(0, 10);
        String fecha2sub = fecha2.substring(0, 10);
        String fecha1Final = "";
        String fecha2Final = "";
        LocalDate localDate1;
        LocalDate localDate2;
        LocalDateTime localDateTime1;
        LocalDateTime localDateTime2;
        Period period;
        Duration duration;

        try {
            localDate1 = LocalDate.parse(fecha1sub,  DateTimeFormatter.ofPattern("dd/MM/yyyy"));

            localDate2 = LocalDate.parse(fecha2sub,  DateTimeFormatter.ofPattern("dd/MM/yyyy"));

            if (txtHora1.getText().isEmpty()) {
                localDateTime1 = LocalDateTime.parse(fecha1 + " 00:00:00", DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss"));
                fecha1Final = fecha1.concat(" 00:00:00");
            } else {
                localDateTime1 = LocalDateTime.parse(fecha1 + " " + txtHora1.getText() + ":00", DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss"));
                fecha1Final = fecha1.concat(" " + txtHora1.getText() + ":00");
            }
            
            if(txtHora2.getText().isEmpty() && txtFecha2.getText().contains(":")){
                   localDateTime2 = LocalDateTime.parse(fecha2 , DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss"));
                   fecha2Final = fecha2;
            } else if (txtHora2.getText().isEmpty()) {
                localDateTime2 = LocalDateTime.parse(fecha2 + " 00:00:00", DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss"));
                fecha2Final = fecha2.concat(" 00:00:00");
            } else {
                localDateTime2 = LocalDateTime.parse(fecha2 + " " + txtHora2.getText() + ":00", DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss"));
                fecha2Final = fecha2.concat(" " + txtHora2.getText() + ":00" );
            }

            period = Period.between(localDate1, localDate2);
            duration = Duration.between(localDateTime1, localDateTime2);
            
            comprobar(localDate1, localDate2);

            txtFecha1.setText("");
            txtFecha2.setText("");

            txtMostrar.setText(" Entre " + fecha1Final + " y " + fecha2Final + " Han pasado: \n - Años: " + period.getYears() + "\n - Días: " + period.getDays() + "\n - Horas: " + duration.toHours()
                    + "\n - Minutos: " + duration.toMinutes() + "\n - Segundos: " + duration.toSeconds());

        } catch (DateTimeParseException e) {
            txtMostrar.setText(" ERROR! El formato ingresado es inválido");
            e.printStackTrace();
            return;
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualActionPerformed
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        LocalDateTime fechaActual = LocalDateTime.now();

        String fecha = fechaActual.format(formatter);
        txtFecha2.setText(fecha);
    }//GEN-LAST:event_btnActualActionPerformed

    private void comprobar(LocalDate fecha1, LocalDate fecha2) {
        if (fecha1.isAfter(fecha2)) {
            txtMostrar.setForeground(Color.red);
            txtMostrar.setText("ERROR! La primer fecha ingresada es mayor a la fecha dos.");
            throw new RuntimeException("ERROR");
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActual;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtFecha1;
    private javax.swing.JTextField txtFecha2;
    private javax.swing.JTextField txtHora1;
    private javax.swing.JTextField txtHora2;
    private javax.swing.JTextArea txtMostrar;
    // End of variables declaration//GEN-END:variables
}
